# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "robertminer"

# URL
baseurl:            "robertminer.me"
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           rdiscount

# Navigation
nav:
  - name:           "TIL Stuff"
    href:           "/til-stuff"
  - name:           "Riviera 4 Media"
    href:           "//riviera4media.com"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
